auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:categories/:title

title: 李思_壹玖捌柒's Blog
url: http://www.lisi1987.com
feed: /atom.xml
author_info: <a href="http://www.lisi1987.com/">李思_壹玖捌柒</a>

follow me:
    - github
    - twitter
    - weibo